import type { ChecklistTemplate } from '@/types/index'

export const villaamilDeparture: ChecklistTemplate = {
  id: 'departure',
  title: 'Cierre del piso',
  subtitle: 'Villaamil · Madrid',
  description: 'Checklist de cierre antes de salir de Madrid',
  icon: '🔒',
  completionMessage: '¡El piso ha quedado cerrado correctamente! Buen viaje.',
  notesLabel: 'Notas del cierre',
  notesPlaceholder: 'Estado del piso, incidencias, recordatorios para la próxima vez…',
  builtIn: true,
  createdAt: '2025-01-01T00:00:00.000Z',
  updatedAt: '2025-01-01T00:00:00.000Z',
  sections: [
    {
      id: 'dormitorio',
      title: 'Dormitorio',
      icon: '🛏',
      order: 1,
      tasks: [
        { id: 'dorm-1', title: 'Desenchufar los ventiladores', critical: true, order: 1 },
        { id: 'dorm-2', title: 'Asegurarse de que TODOS los controles remotos de los ventiladores estén en sus soportes', order: 2 },
        { id: 'dorm-3', title: 'Desenchufar el router', order: 3 },
        { id: 'dorm-4', title: 'Guardar el router en la gaveta de mi cama', note: 'En la gaveta más cercana al armario está la caja del router', order: 4 },
        { id: 'dorm-5', title: 'Revisar que no quede ningún aparato enchufado innecesariamente', order: 5 },
        { id: 'dorm-6', title: 'Apagar todas las luces', critical: true, order: 6 },
      ],
    },
    {
      id: 'bano',
      title: 'Baño',
      icon: '🚿',
      order: 2,
      tasks: [
        { id: 'bano-1', title: 'Comprobar que todos los grifos están cerrados', critical: true, order: 1 },
        { id: 'bano-2', title: 'Revisar que no haya fugas', order: 2 },
        { id: 'bano-3', title: 'Apagar el calentador de agua', critical: true, order: 3 },
      ],
    },
    {
      id: 'salon',
      title: 'Salón',
      icon: '🛋',
      order: 3,
      tasks: [
        { id: 'salon-1', title: 'Revisar que no quede ningún electrodoméstico enchufado', order: 1 },
        { id: 'salon-2', title: 'Cerrar todas las ventanas', critical: true, order: 2 },
        { id: 'salon-3', title: 'Bajar las persianas', order: 3 },
      ],
    },
    {
      id: 'cocina',
      title: 'Cocina',
      icon: '🍽',
      order: 4,
      tasks: [
        { id: 'coc-1', title: 'Comprobar que no quedan alimentos perecederos', order: 1 },
        { id: 'coc-2', title: 'Vaciar el frigorífico', order: 2 },
        { id: 'coc-3', title: 'Limpiar el interior del frigorífico', order: 3 },
        { id: 'coc-4', title: 'Poner el frigorífico en 0', order: 4 },
        { id: 'coc-5', title: 'Dejar las puertas del frigorífico abiertas', order: 5 },
        { id: 'coc-6', title: 'Vaciar el congelador si procede', order: 6 },
        { id: 'coc-7', title: 'Desenchufar el air fryer', order: 7 },
        { id: 'coc-8', title: 'Desenchufar el microondas y dejar la puerta entreabierta', order: 8 },
        { id: 'coc-9', title: 'Revisar que no quede ningún electrodoméstico enchufado', order: 9 },
        { id: 'coc-10', title: 'Revisar grifos de cocina', critical: true, order: 10 },
      ],
    },
    {
      id: 'lavadero',
      title: 'Lavadero',
      icon: '🧺',
      order: 5,
      tasks: [
        { id: 'lav-1', title: 'Vaciar la lavadora', order: 1 },
        { id: 'lav-2', title: 'Dejar la puerta de la lavadora entreabierta', order: 2 },
        { id: 'lav-3', title: 'Vaciar el lavavajillas si aplica', order: 3 },
        { id: 'lav-4', title: 'Dejar la puerta del lavavajillas entreabierta', order: 4 },
        { id: 'lav-5', title: 'Cerrar las llaves de paso de la lavadora y el lavavajillas si existen', order: 5 },
      ],
    },
    {
      id: 'balcon',
      title: 'Balcón',
      icon: '🌿',
      order: 6,
      tasks: [
        { id: 'bal-1', title: 'Cerrar la puerta del balcón', critical: true, order: 1 },
        { id: 'bal-2', title: 'Comprobar persianas del balcón', order: 2 },
      ],
    },
    {
      id: 'instalaciones',
      title: 'Instalaciones generales',
      icon: '💧',
      order: 7,
      tasks: [
        { id: 'gen-1', title: 'Cerrar la llave general del agua', critical: true, note: 'Preguntarle a Carlos dónde está', order: 1 },
        { id: 'gen-2', title: 'Sacar toda la basura', order: 2 },
      ],
    },
    {
      id: 'puerta',
      title: 'Puerta principal',
      icon: '🔒',
      order: 8,
      tasks: [
        { id: 'puer-1', title: 'Cerrar la puerta principal', critical: true, order: 1 },
        { id: 'puer-2', title: 'Dar todas las vueltas de llave', critical: true, order: 2 },
        { id: 'puer-3', title: 'Verificar que la puerta ha quedado bien cerrada', order: 3 },
      ],
    },
    {
      id: 'revision',
      title: 'Última revisión',
      icon: '✅',
      order: 9,
      tasks: [
        { id: 'rev-1', title: 'Recorrer todas las habitaciones', order: 1 },
        { id: 'rev-2', title: 'Comprobar una última vez luces, ventanas y enchufes', order: 2 },
        { id: 'rev-3', title: 'Llevar todas las llaves necesarias', order: 3 },
        { id: 'rev-4', title: 'Grabar un vídeo del recorrido final del piso', critical: true, order: 4 },
        { id: 'rev-5', title: 'Hacer una foto de la puerta cerrada antes de salir', critical: true, order: 5 },
      ],
    },
  ],
}
